### ISSUE TITLE
Can not install requirements

### ISSUE THREAD

**Issue by kascodingNL** [xMistt/fortnitepy-bot#100]
At the point I do pip install fortnitepy, it says "Could not find a version that satisfies requirement fortnitepy (from versions: )"

**Comment by FloGo3308** [comment]
You could try to use pip3 instead of pip. I think it tries to find a python 2 version of fortnitepy, but that does'nt exist.

**Comment by kascodingNL** [comment]
Thanks @FloGo3308! This solved this indeed!

Happy coding :)

**Comment by FloGo3308** [comment]
Graag gedaan ;)

**Comment by kascodingNL** [comment]
Lolwat je bent Nederlands haha

**Comment by FloGo3308** [comment]
Ja, haha
