### ISSUE TITLE
Trace back (most recent call last) file Fortnite.py”, line 83 <in module>

### ISSUE THREAD

**Issue by fadesz** [xMistt/fortnitepy-bot#102]
It’s not letting me get the bot at all I had it then the next day this happened and I don’t know how to fix it help please
![image](https://user-images.githubusercontent.com/64390013/80328703-161adb80-880e-11ea-944a-f816b0283194.jpg)

**Comment by xMistt** [comment]
That isn't even my bot, reinstall it from **this** GitHub page.

**Comment by fadesz** [comment]
It is yours I downloaded it and it’s still doing the same thing can I contact you on Instagram or something?

**Comment by xMistt** [comment]
Well it clearly isn't there is a massive "PY-BOT" on the front and of course you can't contact me on Instagram. If you need help with the bot you can contact me here or in the discord support server.

Here is a direct download link to the bot: https://github.com/xMistt/fortnitepy-bot/archive/master.zip

**Comment by fadesz** [comment]
![image](https://user-images.githubusercontent.com/64390013/80331506-3babe300-8816-11ea-9d17-3685ad9218e5.jpg)

**Comment by xMistt** [comment]
What the error is & it's cause.
The error: json.decoder.JSONDecodeError is caused by Python not being able to parse the config due to it not being in the correct format.

How to fix the error:
In order to fix this error, make sure your config.json isn't missing any commas, brackets, etc. Here is an example config:

```python
{
   "email": "email@email.com",
   "password": "password1",
   "cid": "CID_022_Athena_Commando_F",
   "bid": "BID_023_Pinkbear",
   "eid": "EID_HiLowWave",
   "banner": "otherbanner28",
   "banner_colour": "defaultcolor15",
   "level": 999,
   "bp_tier": 999999999,
   "status": "Created by xMistt, enjoy!\nSupport server: discord.gg/fnpy",
   "platform": "WIN",
   "debug": false,
   "friendaccept": true
}```
