### ISSUE TITLE
variant styles

### ISSUE THREAD

**Issue by GhoulishChris** [xMistt/fortnitepy-bot#107]
whenever i try to do the edit styles it never works, it only works for purple skull and no other skin, i dont know if thats cause im doing it wrong or anything but if u could maybe explain it? thanks

**Comment by BigBrain21** [comment]
Hello, see the page in the wiki for how to use variants.
https://github.com/xMistt/fortnitepy-bot/wiki/Variants

**Comment by GhoulishChris** [comment]
Thats the problem, that guide doesnt really work/isnt really helping. It there like a better explanation?

**Comment by BigBrain21** [comment]
Most skins require that you put "parts" instead of clothing_color. Hope this helps

**Comment by GhoulishChris** [comment]
That worked thanks, but how would i change the like the other styles (like some skins have many styles)

**Comment by BigBrain21** [comment]
There is a list at the wiki for what you can use for variants. I have found that the most common things to use are parts, clothing_color, and material.

**Comment by GhoulishChris** [comment]
Ok thanks! The materials part worked.
