### ISSUE TITLE
how

### ISSUE THREAD

**Issue by NightPog** [xMistt/fortnitepy-bot#108]
how do i make 2 lines 
![image](https://user-images.githubusercontent.com/64943101/81456722-72acbd80-9161-11ea-900e-2c51c46c75b7.png)

**Comment by BigBrain21** [comment]
I am pretty sure if you say "\n" it will do a newline. So you could set the status to !status Created by xMistt, enjoy!\nSupport server: https://discord.gg/fnpy

**Comment by ArchieMaddog** [comment]
i set my status to say Watching PornHub lmao

**Comment by BigBrain21** [comment]
Uh ok

**Comment by BigBrain21** [comment]
Can you clos4 this discussion now

**Comment by BigBrain21** [comment]
*close

**Comment by maudlovers1** [comment]
It Works now go sub to the_norway blogg

**Comment by BigBrain21** [comment]
no

**Comment by BigBrain21** [comment]
fuck off
