### ISSUE TITLE
Cannot invite bot client to own party.

### ISSUE THREAD

**Issue by xMistt** [xMistt/fortnitepy-bot#11]
You cannot invite the bot to any party, it'll return the error:
`fortnitepy.errors.HTTPException: Code: "errors.com.epicgames.social.party.party_not_found" - Sorry, we couldn't find a party by id <client id>`

This is a problem with the package (fortnitepy) and is being worked on. A workaround is by joining the bot instead of inviting it. Everything else seems to work fine.

**Comment by D4vid1k** [comment]
I can't join

**Comment by xMistt** [comment]
@D4vid1k Try select gamemode or restarting game, if that doesn't work; do the command ``!leave`` and then try to join.

**Comment by xMistt** [comment]
Terbau has said that the patch regarding these issues will go live soon.

**Comment by xMistt** [comment]
``fortnitepy v1.0`` (version bug fixed in) expected to release tomorrow.

> Terbau#8523: i think im releasing v1.0... ...most likely tomorrow so i get some sleep

**Comment by xMistt** [comment]
Issue has been fixed.
