### ISSUE TITLE
Can't change Gamemode and go into a game.

### ISSUE THREAD

**Issue by databyte07** [xMistt/fortnitepy-bot#112]
Can't change Gamemode and go into a game. Last time i could change the mode.

**Comment by AbisGameryt** [comment]
So you mean now we can't go into a game ?

**Comment by databyte07** [comment]
Yes Its says: Loading Content (100%)

**Comment by AbisGameryt** [comment]
I was going to show my friends today but guess I can't but I still think it might be just you and that you should reinstall it

**Comment by databyte07** [comment]
The Bot or Fortnite

**Comment by AbisGameryt** [comment]
Ofc the bot

**Comment by AbisGameryt** [comment]
Does it work now ?

**Comment by databyte07** [comment]
No

**Comment by fazfoxy1** [comment]
The bots cannot go into modes with you and you can't use them to go into unreleased ltms

**Comment by databyte07** [comment]
So. The Bot is useless
