### ISSUE TITLE
!skin and !emote commands do not work

### ISSUE THREAD

**Issue by spinfal** [xMistt/fortnitepy-bot#121]
those seem to be the only commands that dont work, because **!playlist, !hologram, CID/EID, and others seem to work. (they _all_ worked fine before 12.60)**. I checked "logs" and this shows:

`File "fortnite.py", line 283, in event_friend_message
    backendType="AthenaCharacter"`

ive also restarted the bot just to be sure, but no luck.

**Comment by xMistt** [comment]
Can you send the full traceback?

**Comment by spinfal2** [comment]
unfortunately i can no longer find it again, but currently the commands seem to be working fine. now that you mention it, i remember somewhere in the traceback it had BenBotAsync for "get_cosmetic", and at the very bottom it had Attribute: 'str' object has no attribute 'get' (which is a dependacy issue according to a previous closed issue)

sorry for the "botched" and strange response lol :/

**Comment by xMistt** [comment]
I think it occurs when the BenBot API cannot be reached. I'll add a proper error.
