### ISSUE TITLE
ClientUser' object has no attribute '_party

### ISSUE THREAD

**Issue by kaaax0815** [xMistt/fortnitepy-bot#126]
I have the newest version of fortnitepy and Python 3.8.3
Comes in github (ubuntu) and heroku. But not when running it locally on windows 10 (fortnitepy==1.7.1; python==3.7.7)
Edited that skin sets on startup not on party join

Task exception was never retrieved
future: <Task finished name='Task-209' coro=<event_ready() done, defined at fortnite.py:184> exception=AttributeError("'ClientUser' object has no attribute '_party'")>
Traceback (most recent call last):
  File "fortnite.py", line 194, in event_ready
    await client.user.party.me.set_outfit(asset="cid_028_athena_commando_f")
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/fortnitepy/user.py", line 338, in party
    return self._party
AttributeError: 'ClientUser' object has no attribute '_party'

**Comment by kaaax0815** [comment]
Fixed by changing fortnitepy version to 1.7.1
still wondering why its different in newer version

**Comment by xMistt** [comment]
The correct way to fix this would be to install the latest versions of: PartyBot, fortnitepy & BenBotAsync instead of running old versions. :+1:
