### ISSUE TITLE
Error -93

### ISSUE THREAD

**Issue by Foxi07** [xMistt/fortnitepy-bot#130]
![Screenshot (85)](https://user-images.githubusercontent.com/65961809/82909759-fc35fb00-9f69-11ea-986b-8eb6ccd22dbc.png)
when i invite or join my bot error 93 occurs

**Comment by xMistt** [comment]
Do !leave and select gamemode.

**Comment by Foxi07** [comment]
Now came this:
No module named 'fortnitepy.ext.commands.bot'
Failed to import 1 or more modules, running "INSTALL PACKAGES.bat"might fix the issue, if not please create an issue or jointhe support server.

**Comment by Foxi07** [comment]
Now cam this:

> Failed to import 1 or more modules, running "INSTALL PACKAGES.bat"might fix the issue, if not please create an issue or jointhe support server.
