### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Foxi07** [xMistt/fortnitepy-bot#132]
When i start the bot came this: 

> Failed to import 1 or more modules, running "INSTALL PACKAGES.bat"might fix the issue, if not please create an issue or jointhe support server.

**Comment by Azlxy** [comment]
Run "INSTALL PACKAGES.bat".

**Comment by Foxi07** [comment]
I already have it.

**Comment by Foxi07** [comment]
now comes: No module with the name 'fortnitepy.ext.commands.bot'
Failure to import one or more modules by running "INSTALL PACKAGES.bat" can fix the problem. If not, please create a problem or connect the support server.

**Comment by BuRn-sensei-GGT** [comment]
Open Command Prompt and type: pip install fortnitepy
Then run the bot again and see if there is an error.

**Comment by Foxi07** [comment]
It is always when I enter it that: 

> Requirement already satisfied:

**Comment by xMistt** [comment]
Reinstall bot & packages.
