### ISSUE TITLE
how to remove status

### ISSUE THREAD

**Issue by Joe678399** [xMistt/fortnitepy-bot#133]

**Comment by ZeroTwoLovesYou** [comment]
you don't

**Comment by spinfal** [comment]
in the `config.json` file, you will see on line 11 the option to set any default status. 
(alternatively you can use the command `!status`, but using the command isn't permanent)

**Comment by xMistt** [comment]
You can't remove status as its required but you can use: ``Battle Royale Lobby - {party playercount} / {party max playercount}``if you want it to be the same as the official client.
