### ISSUE TITLE
No module named

### ISSUE THREAD

**Issue by Foxi07** [xMistt/fortnitepy-bot#135]
My problem when i start the bot: 

> No module named 'fortnitepy.ext.commands.bot'
Failed to import 1 or more modules, running "INSTALL PACKAGES.bat"might fix the issue, if not please create an issue or jointhe support server.

Im already remove all files, but its don´t helped

**Comment by xMistt** [comment]
Reinstall packages.

**Comment by Foxi07** [comment]
How can i Reinstall

**Comment by Foxi07** [comment]
its don`t helped

> Installing the required packages for the bot!

Gewartet wird 0 Sekunden. Weiter mit beliebiger Taste...
Requirement already up-to-date: fortnitepy in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 1)) (2.0.3)
Requirement already up-to-date: BenBotAsync in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 2)) (2.4.0)
Requirement already up-to-date: crayons in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 3)) (0.3.0)
Requirement already up-to-date: pypresence in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 4)) (4.0.0)
Requirement already up-to-date: psutil in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 5)) (5.7.0)
Requirement already satisfied, skipping upgrade: aiohttp>=3.3 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from fortnitepy->-r requirements.txt (line 1)) (3.6.2)
Requirement already satisfied, skipping upgrade: aioxmpp>=0.10.4 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from fortnitepy->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied, skipping upgrade: aioconsole>=0.1.15 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from fortnitepy->-r requirements.txt (line 1)) (0.1.16)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.8.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from fortnitepy->-r requirements.txt (line 1)) (4.9.0)
Requirement already satisfied, skipping upgrade: colorama in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from crayons->-r requirements.txt (line 3)) (0.4.3)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (19.3.0)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (1.4.2)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (4.7.5)
Requirement already satisfied, skipping upgrade: aiosasl>=0.3 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (0.4.0)
Requirement already satisfied, skipping upgrade: aioopenssl>=0.1 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (0.5.1)
Requirement already satisfied, skipping upgrade: babel~=2.3 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (2.8.0)
Requirement already satisfied, skipping upgrade: dnspython~=1.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied, skipping upgrade: lxml~=4.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied, skipping upgrade: sortedcollections>=0.5 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (1.1.2)
Requirement already satisfied, skipping upgrade: pyOpenSSL in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (19.1.0)
Requirement already satisfied, skipping upgrade: pyasn1 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (0.4.8)
Requirement already satisfied, skipping upgrade: pyasn1_modules in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (0.2.8)
Requirement already satisfied, skipping upgrade: tzlocal~=1.2 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from beautifulsoup4>=4.8.0->fortnitepy->-r requirements.txt (line 1)) (2.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (2.9)
Requirement already satisfied, skipping upgrade: pytz>=2015.7 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from babel~=2.3->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (2020.1)
Requirement already satisfied, skipping upgrade: sortedcontainers in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from sortedcollections>=0.5->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied, skipping upgrade: six>=1.5.2 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (1.14.0)
Requirement already satisfied, skipping upgrade: cryptography>=2.8 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (2.9.2)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from cryptography>=2.8->pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (1.14.0)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\adria\appdata\local\programs\python\python38-32\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (2.20)
Done! Now run START BOT.bat

**Comment by BuRn-sensei-GGT** [comment]
What python version are you running?

**Comment by Foxi07** [comment]
Python 3.8.3

**Comment by BuRn-sensei-GGT** [comment]
Ok, In the old readme it said that 3.8.x is very buggy. Try using 3.7 or 3.6.

**Comment by Foxi07** [comment]
okay i try it

**Comment by Foxi07** [comment]
thank you it's fine now!

**Comment by Foxi07** [comment]
but now came the error message -39
![Screenshot (85)](https://user-images.githubusercontent.com/65961809/83065699-3388d280-a064-11ea-9220-d4c1c21e3c0c.png)

**Comment by BuRn-sensei-GGT** [comment]
I don't know how to help with this.

You could try inviting the bot then promoting it to party leader.

**Comment by Foxi07** [comment]
I think it's due to the fortnite account

**Comment by Foxi07** [comment]
when i invite the bot the same thing happens
