### ISSUE TITLE
Cannot GET /id/api/exchange

### ISSUE THREAD

**Issue by heheboi69** [xMistt/fortnitepy-bot#142]
when i try to get my exchange code i get "Cannot GET /id/api/exchange"

pls help
![help](https://user-images.githubusercontent.com/63461297/83424158-b5964400-a434-11ea-8767-00a708180891.png)

**Comment by BigBrain21** [comment]
In the discord https://discord.gg/fnpy follow the directions in the #authorization-code channel.

**Comment by xMistt** [comment]
You don't get exchange codes anymore.
