### ISSUE TITLE
VTIDs

### ISSUE THREAD

**Issue by vvareo** [xMistt/fortnitepy-bot#15]
VTIDs don't work so, for example, I send the bot VTID_162_Tactical_StyleB and it does nothing happens so I looked at the code and i found "Warning: This feature is not supported, please use !variants" and I submitted a suggestion on discord to fix VTIDs and was told to create an issue on Github page so can you fix VTIDs or at least tell me how !variants work because the wiki did not help much

**Comment by vvareo** [comment]
![● fortnite py - Visual Studio Code 9_01_2020 2_28_46 AM (2)_LI](https://user-images.githubusercontent.com/44335189/72396518-044a8680-3791-11ea-80ed-bc51525d9af9.jpg)

**Comment by xMistt** [comment]
I seem to have not implemented the ``vtid_to_variants`` function into [BenBotAsync](https://github.com/xMistt/BenBot). Also, the deprecated thing isn't what is causing the error. That's just a notice since VTIDs aren't recommended.

**Comment by xMistt** [comment]
Fixed in most recent patch.
