### ISSUE TITLE
I can't setup the bot 

### ISSUE THREAD

**Issue by usergraG** [xMistt/fortnitepy-bot#152]
ive got the email  and password correct but when i run it it asks for an authentication code for (said email) and i do not know what this means, please help.

**Comment by teorailin** [comment]
You need to go to https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode

and use the bot account, then copy this.
![seO9cr_NRlaRKWXdm2SIhw](https://user-images.githubusercontent.com/56972441/84986336-b3273000-b13e-11ea-9375-fbf39287e921.png)

**Comment by teorailin** [comment]
and that is the authentication code
