### ISSUE TITLE
Add Add arguments to !copy command

### ISSUE THREAD

**Issue by orangejuiceondiscord** [xMistt/fortnitepy-bot#162]
I know this isn't a bug but you should add the arguments "Permanent" and "Temporary"

**Comment by xMistt** [comment]
What would these arguments be for?

**Comment by orangejuiceondiscord** [comment]
So if your lobby bot has a similar name as someone else you can have the lobby bot have the same cosmetics without finding the id's and make it permanent.

**Comment by xMistt** [comment]
Make it so the bot will forever copy that persons cosmetics or were their cosmetics at the time of executing the command forever?

**Comment by orangejuiceondiscord** [comment]
The bot would wear their cosmetics forever at the time of executing the command until the config.json file is changed or the command is executed again.

**Comment by zw5** [comment]
Maybe it means copy the cosmitics to the json file and set that as the default party config

**Comment by orangejuiceondiscord** [comment]
The command would copy the cosmetics to the JSON file, not you.

**Comment by xMistt** [comment]
I'll keep it in mind but I'll close this issue for now.
