### ISSUE TITLE
Stuck in matchmaking

### ISSUE THREAD

**Issue by lharx** [xMistt/fortnitepy-bot#163]
When player and bot is ready matchmaking is stuck in loading content100%

**Comment by fazfoxy1** [comment]
Bot isn't meant to go in games anyway

**Comment by fazfoxy1** [comment]
Not a issue

**Comment by suzanfisch** [comment]
They dont connect to matchmaking

**Comment by lharx** [comment]
Oohhhh big ooooffff srry

**Comment by LupusLeaks** [comment]
Its okay :)
