### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by MelloModz** [xMistt/fortnitepy-bot#165]
so where am i finding my device auth?

**Comment by Tommy3344** [comment]
1. Click the link below and log in to the account you want an authorization code for.
2. Copy the code from the redirectUrl value (http://prntscr.com/srbujz).

Click This: https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode
