### ISSUE TITLE
error when i try to run

### ISSUE THREAD

**Issue by Bentnand** [xMistt/fortnitepy-bot#167]
Hello. I  have a Bug that when I try to run Fortnite.py from START BOT.bat, it will just say error and stop.
I'm good at Python but honestly, I really don't know what happened.
have a fortnite.py and error log
[errorlog.zip](https://github.com/xMistt/fortnitepy-bot/files/4919818/errorlog.zip)
.
I would like to have a Bug label on it.
sorry for many edits.

**Comment by xMistt** [comment]
Downgrade from 3.8.4 to any version above 3.6.0.
