### ISSUE TITLE
any way to bypass captcha?

### ISSUE THREAD

**Issue by blue-jai** [xMistt/fortnitepy-bot#173]
everytime i try to start the bot it says "Captcha was enforced. Please enter a valid authorization code for (email)

is there anything i can do to bypass this?

**Comment by fazfoxy1** [comment]
https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode go to this website and copy the code instructions on how to are in the discord (discord.gg/fnpy) in the #authorization-code

**Comment by blue-jai** [comment]
thanks so much! i ended up figuring it out on my own but thanks either way!
