### ISSUE TITLE
Question: Send PartyInvitation on IncomingPendingFriend

### ISSUE THREAD

**Issue by kaaax0815** [xMistt/fortnitepy-bot#175]
Sorry that this is not an issue, but im curious tho.

I cant find any API for sending an invitation in the fortnitepy docs

So I ask you how to send and PartyInvitation on an IncomingPendingFriend
---
## Edit:
fortnite.py.Friend invite() is the right thing
### New Problem:
How do I set the name to IncomingPendingFriend.display_name
---
## Edit2:
Code: `await fortnitepy.Friend.invite(
            display_name=request.display_name
        )`

Error: `Task exception was never retrieved
future: <Task finished coro=<event_friend_request() done, defined at fortnite.py:257> exception=TypeError("invite() got an unexpected keyword argument 'display_name'")>
Traceback (most recent call last):
  File "fortnite.py", line 264, in event_friend_request
    display_name=request.display_name
TypeError: invite() got an unexpected keyword argument 'display_name'`

It says that display_name is unexpected, but how else should i define the receiver

**Comment by xMistt** [comment]
You need to get an instance of the friend object, if you accept a pending friend request, the method itself returns the newly created Friend object so you can do:

```python
friend = await pending.accept()
await friend.invite()
```
Hope this helps!
