### ISSUE TITLE
the bot does'nt put on skins and emotes when invited

### ISSUE THREAD

**Issue by NathanTurnYT** [xMistt/fortnitepy-bot#178]
it seems like there is something with pickaxe_id

here is my log:

[PartyBot] [22:32:56] PartyBot made by xMistt. Massive credit to Terbau for creating the library.
[PartyBot] [22:32:56] Discord server: https://discord.gg/fnpy - For support, questions, etc.
[PartyBot] [22:33:00] Client ready as NTeam_PrivateBOT.
Task exception was never retrieved
future: <Task finished name='Task-119' coro=<event_party_member_join() done, defined at C:\Users\NT\Downloads\fortnitepy-bot-master (5)\fortnitepy-bot-master\fortnite.py:289> exception=KeyError('pickaxe_id')>
Traceback (most recent call last):
  File "C:\Users\NT\Downloads\fortnitepy-bot-master (5)\fortnitepy-bot-master\fortnite.py", line 291, in event_party_member_join
    await BenBotAsync.set_default_loadout(client, data, member)
  File "C:\Users\NT\AppData\Local\Programs\Python\Python38-32\lib\site-packages\BenBotAsync\__init__.py", line 103, in set_default_loadout
    config['pickaxe_id']
KeyError: 'pickaxe_id'
[PartyBot] [22:33:16] Accepted party invite from Replay Watcher.

**Comment by xMistt** [comment]
Can you send your `config.json` file?

**Comment by xMistt** [comment]
Re-open again if you ever respond.
