### ISSUE TITLE
i have an issue with the start 

### ISSUE THREAD

**Issue by YagaGameplaysYT** [xMistt/fortnitepy-bot#180]
i have this problem when i start the bot Captcha was enforced. Please enter a valid authorization code for .... idk how i can solve it thx

**Comment by wavy0** [comment]
you need to get an authorization code from https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode and copy the text from fnauth?code=

**Comment by YagaGameplaysYT** [comment]
and what do I do next?

**Comment by wavy0** [comment]
Start the bot and copy the text from fnauth?code=  and then paste it in the lobby bot.

**Comment by YagaGameplaysYT** [comment]
[PartyBot] [11:51:42] [ERROR] Invalid authorization code supplied

**Comment by YagaGameplaysYT** [comment]
i have this problem

**Comment by wavy0** [comment]
I can't help you anymore :/

**Comment by YagaGameplaysYT** [comment]
f

**Comment by YagaGameplaysYT** [comment]
i solve that problem but now i have another xd : NameError: name 'incoming_pending_friends' is not defined

**Comment by jessyhearn** [comment]
Je peut aller dans le groupe

**Comment by xMistt** [comment]
Fixed, I'm an idiot.
