### ISSUE TITLE
adding commands?

### ISSUE THREAD

**Issue by 5coolguy5** [xMistt/fortnitepy-bot#183]
how?

**Comment by teenari** [comment]
😳 how?

**Comment by wavy0** [comment]
bruh

**Comment by AtieP** [comment]
```py
@commands.command(name="command_name")
async def command_function(self, ctx, parameters) -> None:
    # function body
    pass```

**Comment by wavy0** [comment]
adding commands?
how? 
wtf does that even mean can i get a answer pls

**Comment by teenari** [comment]
> adding commands?
> how?
> wtf does that even mean can i get a answer pls
just making a function where it does stuff?

**Comment by xMistt** [comment]
You can add your own cogs in fortnite.py.
