### ISSUE TITLE
Error: Older Version of fortnite

### ISSUE THREAD

**Issue by freeezy-lab** [xMistt/fortnitepy-bot#189]
I updated my bot after update 14.10 (Executed 'INSTALL PACKAGES.bat' as well)
When I now try to join him it says 'Can't join ... Error: ... is using an older version of the game'

**Comment by Tommy3344** [comment]
just invite it then leave the party then join back

**Comment by wavy0** [comment]
i dont think fortnitepy has been updated to the newest version, im not sure

**Comment by xMistt** [comment]
Reinstall packages.

**Comment by teenari** [comment]
> I updated my bot after update 14.10 (Executed 'INSTALL PACKAGES.bat' as well)
> When I now try to join him it says 'Can't join ... Error: ... is using an older version of the game'

sorry i had my pp hanging that's prob why

**Comment by KoalaMans** [comment]
> Reinstall packages.

it does the same to me and doesnt work reinstalling it didnt do anything

**Comment by wavy0** [comment]
have you ever heard of fortnitepy hasn't updated

**Comment by wavy0** [comment]
ignore that  comment i made before, reinstall packages probably every day you want to use the bot and see if it works i guess
