### ISSUE TITLE
Captcha was enforced.

### ISSUE THREAD

**Issue by FunDeadsDev** [xMistt/fortnitepy-bot#190]
Do you have the link of auth bot :(

"Please enter a valid authorization code"

**Comment by fazfoxy1** [comment]
https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode

**Comment by ScriptHTML** [comment]
Why is people this dumb? If you cared about going into de Discord, you would have the instructions. @ScorpionTeam1

**Comment by wavy0** [comment]
typo lol
