### ISSUE TITLE
doesn't start up

### ISSUE THREAD

**Issue by Civilux** [xMistt/fortnitepy-bot#195]
![image](https://user-images.githubusercontent.com/67658986/101096370-25de7780-35c8-11eb-8806-876290662001.png)

**Comment by xoElf** [comment]
Same issue but i cant even pass "[PartyBot] [20:52:31] PartyBot made by xMistt. Massive credit to Terbau for creating the library.
[PartyBot] [20:52:31] Discord server: https://discord.gg/8heARRB - For support, questions, etc."

**Comment by xMistt** [comment]
Duplicate of https://github.com/xMistt/fortnitepy-bot/issues/201. See solution there.
