### ISSUE TITLE
bot won't open anymore

### ISSUE THREAD

**Issue by osama1433** [xMistt/fortnitepy-bot#202]
Collecting fortnitepy (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/74/bb/2bc68ad08b7638aca9b8747f552fbb01fc2fc740c756c84a7cee5d8fe647/fortnitepy-3.3.5.tar.gz
Collecting BenBotAsync (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/98/50/9b90f2d689ee2221457f1348c2d18014ac383bda0799ed08d1b759147720/BenBotAsync-2.6.0-py3-none-any.whl
Collecting crayons (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5b/0d/e3fad4ca1de8e70e06444e7d777a5984261e1db98758b5be3e8296c03fe9/crayons-0.4.0-py2.py3-none-any.whl
Collecting pypresence (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ee/41/5a5437bad7c89faade30115f90689a734d77857634962ffa569ef0b209fe/pypresence-4.0.0.tar.gz
Collecting FortniteAPIAsync (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/66/d3/e1124bf7c09998b1a5b97f524d404c44353b75d8ac90935b7ad722285c82/FortniteAPIAsync-0.1.6-py3-none-any.whl
Collecting aiofiles (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ba/21/df5eae4b6db2eb00d58428dd7f793ecbf99942fcafcea141cbf108fa72f4/aiofiles-0.6.0-py3-none-any.whl
Requirement not upgraded as not directly required: aiohttp>=3.3 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from fortnitepy->-r requirements.txt (line 1)) (3.7.3)
Collecting aioxmpp>=0.10.4 (from fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/dc/0c/987a30bf6d68f9b4ec2bda3ddc0ba7d34c9b0ee5aca91ec3d0f919f18fb2/aioxmpp-0.11.0.tar.gz
Collecting aioconsole>=0.1.15 (from fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/5a/12/fce04ddc0a8ebd6482e5ec293d8bda47c9e05c82826b061f7b73523b8601/aioconsole-0.3.1.tar.gz
Collecting colorama (from crayons->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Requirement not upgraded as not directly required: async-timeout<4.0,>=3.0 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (3.0.1)
Requirement not upgraded as not directly required: typing-extensions>=3.6.5 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (3.7.4.3)
Requirement not upgraded as not directly required: attrs>=17.3.0 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (20.3.0)
Requirement not upgraded as not directly required: yarl<2.0,>=1.0 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (1.6.3)
Requirement not upgraded as not directly required: multidict<7.0,>=4.5 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (5.1.0)
Requirement not upgraded as not directly required: chardet<4.0,>=2.0 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (3.0.4)
Requirement not upgraded as not directly required: aiosasl>=0.3 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (0.4.1)
Collecting aioopenssl>=0.1 (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b1/34/e28adb7600d8ccff787a841241bc2591a3661a66e4f171d38956c0cd3002/aioopenssl-0.5.1.tar.gz
Collecting babel~=2.3 (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/dd/a5/81076e10b5ef74493cf08a8e419e61b64324c9c55db4aa7f89c0240c4873/Babel-2.9.0-py2.py3-none-any.whl
Collecting dnspython~=1.0 (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl
Collecting lxml~=4.0 (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c9/a0/67f5435f19d0817bdc313782a5aa8442984cf49acc126697c8036ac25299/lxml-4.6.2-cp37-cp37m-win_amd64.whl
Collecting sortedcollections>=0.5 (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ea/f1/831fa9763afc85d3065557762824490d6e4d1afe1a56e0f053a568ae0cb5/sortedcollections-1.2.1-py2.py3-none-any.whl
Collecting pyOpenSSL (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b2/5e/06351ede29fd4899782ad335c2e02f1f862a887c20a3541f17c3fa1a3525/pyOpenSSL-20.0.1-py2.py3-none-any.whl
Collecting pyasn1 (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Collecting pyasn1_modules (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/95/de/214830a981892a3e286c3794f41ae67a4495df1108c3da8a9f62159b9a9d/pyasn1_modules-0.2.8-py2.py3-none-any.whl
Collecting tzlocal~=1.2 (from aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz
Requirement not upgraded as not directly required: idna>=2.0 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.3->fortnitepy->-r requirements.txt (line 1)) (3.0)
Collecting pytz>=2015.7 (from babel~=2.3->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/89/06/2c2d3034b4d6bf22f2a4ae546d16925898658a33b4400cfb7e2c1e2871a3/pytz-2020.5-py2.py3-none-any.whl
Collecting sortedcontainers (from sortedcollections>=0.5->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/20/4d/a7046ae1a1a4cc4e9bbed194c387086f06b25038be596543d026946330c9/sortedcontainers-2.3.0-py2.py3-none-any.whl
Requirement not upgraded as not directly required: six>=1.5.2 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (1.15.0)
Collecting cryptography>=3.2 (from pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b7/82/f7a4ddc1af185936c1e4fa000942ffa8fb2d98cff26b75afa7b3c63391c4/cryptography-3.3.1.tar.gz
  Installing build dependencies ... done
Requirement not upgraded as not directly required: cffi>=1.12 in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from cryptography>=3.2->pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (1.14.4)
Requirement not upgraded as not directly required: pycparser in c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages (from cffi>=1.12->cryptography>=3.2->pyOpenSSL->aioxmpp>=0.10.4->fortnitepy->-r requirements.txt (line 1)) (2.20)
aioxmpp 0.11.0 has requirement multidict<5,>=2.0, but you'll have multidict 5.1.0 which is incompatible.
Installing collected packages: cryptography, pyOpenSSL, aioopenssl, pytz, babel, dnspython, lxml, sortedcontainers, sortedcollections, pyasn1, pyasn1-modules, tzlocal, aioxmpp, aioconsole, fortnitepy, BenBotAsync, colorama, crayons, pypresence, FortniteAPIAsync, aiofiles
  Running setup.py install for cryptography ... error
    Complete output from command C:\Users\Gamer\AppData\Local\Programs\Python\Python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Gamer\\AppData\\Local\\Temp\\pip-install-sjqenhoa\\cryptography\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Gamer\AppData\Local\Temp\pip-record-dvlp96d1\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cryptography
    copying src\cryptography\exceptions.py -> build\lib.win-amd64-3.7\cryptography
    copying src\cryptography\fernet.py -> build\lib.win-amd64-3.7\cryptography
    copying src\cryptography\utils.py -> build\lib.win-amd64-3.7\cryptography
    copying src\cryptography\__about__.py -> build\lib.win-amd64-3.7\cryptography
    copying src\cryptography\__init__.py -> build\lib.win-amd64-3.7\cryptography
    creating build\lib.win-amd64-3.7\cryptography\hazmat
    copying src\cryptography\hazmat\_der.py -> build\lib.win-amd64-3.7\cryptography\hazmat
    copying src\cryptography\hazmat\_oid.py -> build\lib.win-amd64-3.7\cryptography\hazmat
    copying src\cryptography\hazmat\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat
    creating build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\base.py -> build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\certificate_transparency.py -> build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\extensions.py -> build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\general_name.py -> build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\name.py -> build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\ocsp.py -> build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\oid.py -> build\lib.win-amd64-3.7\cryptography\x509
    copying src\cryptography\x509\__init__.py -> build\lib.win-amd64-3.7\cryptography\x509
    creating build\lib.win-amd64-3.7\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends
    creating build\lib.win-amd64-3.7\cryptography\hazmat\bindings
    copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings
    creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\poly1305.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives
    creating build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\aead.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dh.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ed25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ed448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ocsp.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\poly1305.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\backends\openssl
    creating build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\bindings\openssl
    creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ed25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ed448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\x25519.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\x448.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\asymmetric
    creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\aead.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\ciphers
    creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\scrypt.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\kdf
    creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
    copying src\cryptography\hazmat\primitives\serialization\base.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
    copying src\cryptography\hazmat\primitives\serialization\pkcs12.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
    copying src\cryptography\hazmat\primitives\serialization\pkcs7.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
    copying src\cryptography\hazmat\primitives\serialization\ssh.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
    copying src\cryptography\hazmat\primitives\serialization\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\serialization
    creating build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win-amd64-3.7\cryptography\hazmat\primitives\twofactor
    running egg_info
    writing src\cryptography.egg-info\PKG-INFO
    writing dependency_links to src\cryptography.egg-info\dependency_links.txt
    writing requirements to src\cryptography.egg-info\requires.txt
    writing top-level names to src\cryptography.egg-info\top_level.txt
    reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files found matching 'vectors'
    warning: no previously-included files matching '*' found under directory 'vectors'
    warning: no previously-included files matching '*' found under directory '.github'
    warning: no previously-included files found matching 'release.py'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'rtd-requirements.txt'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '*' found under directory '.zuul.d'
    warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
    writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.7\\Release\\_padding.c'
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    generating cffi module 'build\\temp.win-amd64-3.7\\Release\\_openssl.c'
    building '_openssl' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cryptography:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) Read https://cryptography.io/en/latest/installation.html for specific
           instructions for your platform.
        3) Check our frequently asked questions for more information:
           https://cryptography.io/en/latest/faq.html
        =============================DEBUG ASSISTANCE=============================

    ----------------------------------------
Command "C:\Users\Gamer\AppData\Local\Programs\Python\Python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Gamer\\AppData\\Local\\Temp\\pip-install-sjqenhoa\\cryptography\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Gamer\AppData\Local\Temp\pip-record-dvlp96d1\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Gamer\AppData\Local\Temp\pip-install-sjqenhoa\cryptography\
You are using pip version 10.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by xMistt** [comment]
Your solution is right there.

> ```python
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":
> 
> https://visualstudio.microsoft.com/visual-cpp-build-tools/
> ```

**Comment by xMistt** [comment]
Another fix I found is to update pip though.
