### ISSUE TITLE
Fortnite authorization code

### ISSUE THREAD

**Issue by KazamiBlinder** [xMistt/fortnitepy-bot#206]
Whenever I try to start the bot, it asks for the authorization code, which I don't know what it is. I've tried to paste the exchange code, but it seems to not work. Can you help me?

**Comment by Tommy3344** [comment]
How to retrieve an authorization code:


1. Click the link below and log in to the account you want an authorization code for.
2. Copy the code from the redirectUrl value (http://prntscr.com/srbujz).


Link: https://www.epicgames.com/id/logout?redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fredirect%253FclientId%253D3446cd72694c4a4485d81b77adbb2141%2526responseType%253Dcode

**Comment by xMistt** [comment]
Solved.
