### ISSUE TITLE
Impossible to join the bot

### ISSUE THREAD

**Issue by GLWine** [xMistt/fortnitepy-bot#213]
I tried to add myself to the bot, but Fortnite warned me that the bot is in play on an older version of mine ... now what do I do?
![Immagine 2021-03-20 142230](https://user-images.githubusercontent.com/54741923/111870939-d7db5d00-8987-11eb-89e2-e81f7298ada9.jpg)

**Comment by NathanTurnYT** [comment]
You can still invite him

**Comment by KoalaMans** [comment]
Same happened to me

**Comment by GLWine** [comment]
it happens very often when I'm alone in the lobby

**Comment by wavy0** [comment]
reinstall packages ig  every day until it works

**Comment by xMistt** [comment]
Privacy is broken or something, I'll look into it.

**Comment by xMistt** [comment]
Fixed in https://github.com/xMistt/fortnitepy-bot/commit/4a0e8b28d0094fd8fe8db7967e8c51e5d689aff8.
