### ISSUE TITLE
partybot only works in windows but in ubuntu fails

### ISSUE THREAD

**Issue by PinaYTTT** [xMistt/fortnitepy-bot#216]
Hi i have this ploblem
![image](https://user-images.githubusercontent.com/51247100/113374117-b93f7380-9342-11eb-9694-48a8e2765c09.png)
Someone can help me

**Comment by wavy0** [comment]
maybe try reinstalling packages

**Comment by xMistt2** [comment]
Sounds stupid but do you have your /PartyBot directory? I originally made the bot and ran it on a Unix machine for 2 years so I know it works/worked on it.
