### ISSUE TITLE
FortnitePY dependence not installing proprely

### ISSUE THREAD

**Issue by Furdox** [xMistt/fortnitepy-bot#226]

**Comment by NathanTurnYT** [comment]
Ok, fixed the problem, however, i cannot login.

"errorCode": "errors.com.epicgames.common.oauth.invalid_token",
    "errorMessage": "Client id mismatch in credentials for this pin grant",
    "messageVars": [],
    "numericErrorCode": 1012,
    "originatingService": "com.epicgames.account.public",
    "intent": "prod",
    "error_description": "Client id mismatch in credentials for this pin grant",
    "error": "invalid_grant"

**Comment by NathanTurnYT** [comment]
i tried loging in multiple times, didnt work

**Comment by DHyperYT** [comment]
This doesn't work anymore i guess

**Comment by xMistt** [comment]
Fixed in https://github.com/xMistt/fortnitepy-bot/commit/90fed06b3c66113f7e379580e10e46726bf3d02e.
