### ISSUE TITLE
WARRING!

### ISSUE THREAD

**Issue by NrgCristi** [xMistt/fortnitepy-bot#234]
I am warring everyone, Don't use this, i used it and i got banned, Don't use it, If you want to get banned then use it

Fuck You mistxoli

This deserves an 👎

**Comment by FedFer98123** [comment]
Your main account got banned?? How is that possible, you must use a secondary account for the bot, not related to your main one at all.

**Comment by NrgCristi** [comment]
> Your main account got banned?? How is that possible, you must use a secondary account for the bot, not related to your main one at all.

just kidding

**Comment by xMistt** [comment]
This isn't why you got banned, you got banned because you cheated. I've been using the same Epic Games account since 2016 and I've had no issues.

**Comment by NrgCristi** [comment]
> This isn't why you got banned, you got banned because you cheated. I've been using the same Epic Games account since 2016 and I've had no issues.

I don't cheat i just wanted to prank u
