### ISSUE TITLE
asyncio.ProactorEventLoop is not supported

### ISSUE THREAD

**Issue by neurax-serv** [xMistt/fortnitepy-bot#27]
asyncio.ProactorEventLoop is not supported

**Comment by xMistt** [comment]
Unfortunately I can’t fix it due to the issue being with a package called ``fortnitepy``.

Either downgrade to Python 3.6/3.7 or wait for ``fortnitepy`` to be updated.

**Comment by xMistt** [comment]
Fixed in ``fortnitepy`` 1.5.1, reinstall packages.
