### ISSUE TITLE
## Error when trying to join bots parties

### ISSUE THREAD

**Issue by XenSwapperOwner** [xMistt/fortnitepy-bot#39]
### **Issue.**

Cannot join parties and get a error inside the game itself

### **Cause**
Unknown 

### **Solution**
Unknown 

### ### **The error **
Unable to join __________’s party.Error Code -93

**Comment by xMistt** [comment]
Can you recreate it?

**Comment by Harmonysunshine7** [comment]
How to create bots

**Comment by XenSwapperOwner** [comment]
> Can you recreate it?

Wym

**Comment by fazfoxy1** [comment]
he needs you to find a way to always cause it

**Comment by realkyro** [comment]
This error occurs when you're in a lobby with people that play creative.

**Comment by realkyro** [comment]
just leave the lobby and join/invite the bot again
