### ISSUE TITLE
Error don't reseved email (exchange code)

### ISSUE THREAD

**Issue by TopBrian** [xMistt/fortnitepy-bot#46]
Hello ! I don't reseved exchange code with my email :'(

**Comment by xMistt** [comment]
Exchange codes aren't like 2fa codes, you have to retrieve them yourself by doing these steps:

**How can I get an exchange code for my account?**
> You can get an exchange code by clicking the link below, logging in and then copying the visible code. You can generate a new exchange code by refreshing the page if needed.<br>
> https://www.epicgames.com/id/logout?lang=en-US&redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fexchange&lang=en-US
