### ISSUE TITLE
SyntaxError: invalid syntax when trying to launch fortnite.py on mac

### ISSUE THREAD

**Issue by azalvarez03** [xMistt/fortnitepy-bot#54]
Hello everyone,

I am hoping someone that's way smarter than me can help me resolve an issue I have when launching fortnite.py

I installed Python 3.6  and ran the following command 
`python3 -m pip install -U -r requirements.txt`
which I believe is needed to be done to have the correct resources. 

Next I edited config.json to have my bots email address and password.

Finally, I run fortnite.py but fall short in creating a functional bot due to Syntax Errors. 

The errors look like this:
```

******-MacBook-Pro:~ **********$ cd '/Users/**********$/Downloads/fortnite/' && '/usr/bin/pythonw'  '/Users/**********$/Downloads/fortnite/fortnite.py'  && echo Exit status: $? && exit 1
  File "/Users/**********$/Downloads/fortnite/fortnite.py", line 26
    def time() -> strf:
               ^
SyntaxError: invalid syntax
```

Anyone knows how to resolve this issue? Many thanks in advance!

**Comment by xMistt** [comment]
Issue resolved in the discord (was using Python 2.x to open the bot while Python 3.6+ is required).
