### ISSUE TITLE
Unable to change skin

### ISSUE THREAD

**Issue by Dve4Ever** [xMistt/fortnitepy-bot#58]
When i use the !skin command, it wont work and the skin wont change but the other commands do

**Comment by fazfoxy1** [comment]
do commands like !emote also not work?

**Comment by Dve4Ever** [comment]
I havent tried it but im trying to download Python 3.6.0 instead of 3.8.2

**Comment by Dve4Ever** [comment]
![image](https://user-images.githubusercontent.com/37259482/77443154-41e71380-6dc1-11ea-9a44-b36b04dc125c.png)

It comes up with this error still

**Comment by Dve4Ever** [comment]
Emoting doesnt work either but i reinstalled it

**Comment by realkyro** [comment]
Try reinstalling the bot

**Comment by Dve4Ever** [comment]
Like to delete the bot folder and re-download it? Thats what i did

**Comment by Dve4Ever** [comment]
I reinstalled it once again and reinstalled pyton and now its fixed!
