### ISSUE TITLE
Can't Launch the bot

### ISSUE THREAD

**Issue by osama1433** [xMistt/fortnitepy-bot#65]
Can't launch the bot if the name epic of bot are Arabic

**Comment by xMistt** [comment]
It's an issue with fortnitepy. Terbau already knows about it and I think will soon resolve the issue.

**Comment by xMistt** [comment]
A workaround at this time is to change the username of the account to only include non-ascii characters.

**Comment by xMistt** [comment]
Please report the issue at https://github.com/Terbau/fortnitepy please.
