### ISSUE TITLE
Inviting a bot

### ISSUE THREAD

**Issue by ZeroTwoooooo** [xMistt/fortnitepy-bot#68]
Hi its me ya boi ;)
When in a lobby of more then 3 players sometimes when inviting the bot it doesnt join sometimes it does.
So if it doesnt wanna join i have to do !leave or join the bot

**Comment by teorailin** [comment]
Today I invited a bot to a room with more than 6 people and it worked :u

**Comment by teorailin** [comment]
F

**Comment by osama1433** [comment]
1st one plz we need fix asap

**Comment by xMistt** [comment]
I cannot recreate it it works perfectly for me. Do you experience an error?

**Comment by xMistt** [comment]
@teorailin Only post comments which contribute to the issue and are relevant. "F" doesn't help.

**Comment by osama1433** [comment]
i mean +4 players in lobby when i invite a bot it's join a default skin and leave instantly

**Comment by xMistt** [comment]
I cant seem to recreate it, can someone send me cmd output when this happens? :)

**Comment by osama1433** [comment]
Task exception was never retrieved
future: <Task finished coro=<event_party_member_join() done, defined at fortnite.py:189> exception=AttributeError("'NoneType' object has no attribute 'edit_and_keep'",)>
Traceback (most recent call last):
  File "fortnite.py", line 191, in event_party_member_join
    await BenBotAsync.set_default_loadout(client, data, member)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36-32\lib\site-packages\BenBotAsync\__init__.py", line 81, in set_default_loadout
    await party_update_meta.me.edit_and_keep(  # Sets default loadout.
AttributeError: 'NoneType' object has no attribute 'edit_and_keep'

**Comment by xMistt** [comment]
And does this always happen?

**Comment by osama1433** [comment]
Yes
the bot don't want join for +4 players party

**Comment by xMistt** [comment]
Works perfectly fine to me and that error happens after the bot joins.
