### ISSUE TITLE
How to get the EID codes, CID or BID? 

### ISSUE THREAD

**Issue by teorailin** [xMistt/fortnitepy-bot#70]

**Comment by teorailin** [comment]
I mean how to get or where the codes of each skin, dance and backpack
Do you recommend any page or document?

**Comment by MelloModz** [comment]
search up fortnite ids by danilecx

**Comment by MelloModz** [comment]
> I mean how to get or where the codes of each skin, emote and backpack
> Do you recommend any page or document?

fortnite ids by danilecx

**Comment by xMistt** [comment]
When you whisper the bot commands such as ``!skin``, it'll respond with ``Skin set to [cid]`` which you can then use in config.json.

**Comment by teorailin** [comment]
ok thx
