### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AtomicGaming666** [xMistt/fortnitepy-bot#71]
![image](https://user-images.githubusercontent.com/39306849/78463904-169be700-7726-11ea-9cc5-5c73b0022367.png)

WHAT THIS

**Comment by AtomicGaming666** [comment]
how do i get the code

**Comment by xMistt** [comment]
Hey, you're running a fork of the bot. Can you please reinstall the bot if you want support from here? 

You can also join the support server as we have a channel dedicated to exchange code: https://discord.gg/fnpy

**Comment by AtomicGaming666** [comment]
now do i redownload

**Comment by AtomicGaming666** [comment]
and i join the discord

**Comment by xMistt** [comment]
Go to the #bot-support channel in the discord support server.
