### ISSUE TITLE
(this is a question) how can I set the style of a skin?

### ISSUE THREAD

**Issue by teorailin** [xMistt/fortnitepy-bot#75]
like deadpool without mask etc

**Comment by unchilled** [comment]
use the `!variants` command. you can look at the page explaining variants in full [here](https://github.com/xMistt/fortnitepy-bot/wiki/Variants).

here are some examples you can try out:
deadpool without mask: `!variants cid_705_athena_commando_m_donut parts 2`
purple skull trooper: `!variants cid_030_athena_commando_m_halloween clothing_color 1`
pink ghoul trooper: `!variants cid_029_athena_commando_f_halloween material 3`

hope that helps you

**Comment by teorailin** [comment]
ok thx
