### ISSUE TITLE
time elapsed on a match

### ISSUE THREAD

**Issue by lambor590** [xMistt/fortnitepy-bot#76]
When I whisper the bot, for example: !match 4
It sets the state In-game with 4 people left but the time elapsed is the same, and in the console it shows me this:

Task exception was never retrieved
future: <Task finished coro=<event_friend_message() done, defined at fortnite.py:185> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "fortnite.py", line 814, in event_friend_message
    datetime.datetime.utcnow() - datetime.timedelta(minutes=int(args[2]) if len(args) >= 2 else 0)
IndexError: list index out of range

**Comment by xMistt** [comment]
If you whisper the bot just !match, what happens then?

**Comment by lambor590** [comment]
> If you whisper the bot just !match, what happens then?

Then it works, but if I would put a number of players? The time stays at 0

**Comment by xMistt** [comment]
Fixed in commit https://github.com/xMistt/fortnitepy-bot/commit/346bea4d102b26ee801cce2dbfe92a9ec292a682.
