### ISSUE TITLE
It Wont Log Into My Account

### ISSUE THREAD

**Issue by RandomUsername12341234** [xMistt/fortnitepy-bot#80]
i tried to log into the account for the bot, but it only said "Please enter the exchange code for *my email*.
but it wont send it and i cant log into it so the bot wont work...

**Comment by realkyro** [comment]
When you start your bot, it may ask you for an exchange code. Here is an FAQ provided by Terbau.

What is an exchange code?

- An exchange code is a one time usable code that can be used to log into your account. The code expires after 5 minutes. Never share this code with anyone!

How can I get an exchange code for my account?

- You can get an exchange code by clicking the link below, logging in and then copying the visible code. You can generate a new exchange code by refreshing the page if needed.
- https://www.epicgames.com/id/logout?lang=en-US&redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fexchange&lang=en-US

**Comment by RandomUsername12341234** [comment]
Thanks a lot that helped have a nice day.
