### ISSUE TITLE
help

### ISSUE THREAD

**Issue by heheboi69** [xMistt/fortnitepy-bot#84]
Please enter exchange code for <email address>

Where do i find the exchange code?

**Comment by LilithLovesYou** [comment]
You find the exchange token here
https://www.epicgames.com/id/logout?lang=en-US&redirectUrl=https%3A//www.epicgames.com/id/login%3FredirectUrl%3Dhttps%253A%252F%252Fwww.epicgames.com%252Fid%252Fapi%252Fexchange&lang=en-US

(Login with your bot account)
