### ISSUE TITLE
Mac OS

### ISSUE THREAD

**Issue by RUGMJ7443** [xMistt/fortnitepy-bot#92]
is it possible for this to work on mac os I tried it and when I opened the START BOT file it said this:
START BOT.bat: line 1: py: command not found
and
line 2: cmd: command not found
if this dose not work on mac os what os were you talking about in the .README file at the very bottom you said this feature will not work on windows 10 so what os were you talking about?

**Comment by xMistt** [comment]
.bat files don't work on Mac.
