### ISSUE TITLE
Invalid exchange code supplied

### ISSUE THREAD

**Issue by Mistissexy** [xMistt/fortnitepy-bot#97]
Hi, so my bot was working perfectly yesterday then stopped so i tried to re-install it but it keeps saying invalid exchange code supplied. I have tried many different methods to get the exchange code but still no luck my discord is Mist#9758

**Comment by elytraoff** [comment]
same

**Comment by xMistt** [comment]
https://github.com/xMistt/fortnitepy-bot/wiki/Exchange-Code
